# Generated by Django 5.2.14 on 2026-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV / Resume'), ('cover_letter', 'Cover Letter'), ('id_document', 'ID Document'), ('matric', 'Matric Certificate'), ('qualifications', 'Qualifications / Certificates'), ('drivers_licence', "Driver's Licence"), ('police_clearance', 'Police Clearance Certificate'), ('references', 'References'), ('proof_of_address', 'Proof of Address'), ('bank_details', 'Bank Details'), ('z83', 'Z83 Form'), ('certified_copies', 'Certified Copies'), ('saqa', 'SAQA Verification'), ('professional_reg', 'Professional Body Registration'), ('portfolio', 'Portfolio / Work Samples'), ('transcript', 'Academic Transcript'), ('other', 'Other')], max_length=30),
        ),
    ]
