services:
  - type: web
    name: job-hunter
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn job_hunter.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-hunter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GROQ_API_KEY
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
