# Generated by Django 5.2.14 on 2026-05-08 14:11

import apps.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cv', 'CV / Resume'), ('cover_letter', 'Cover Letter'), ('id_document', 'ID Document'), ('matric', 'Matric Certificate'), ('qualifications', 'Qualifications / Certificates'), ('drivers_licence', "Driver's Licence"), ('police_clearance', 'Police Clearance Certificate'), ('references', 'References'), ('proof_of_address', 'Proof of Address'), ('bank_details', 'Bank Details'), ('z83', 'Z83 Form'), ('certified_copies', 'Certified Copies'), ('saqa', 'SAQA Verification'), ('professional_reg', 'Professional Body Registration'), ('portfolio', 'Portfolio / Work Samples'), ('transcript', 'Academic Transcript'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
