# Generated by Django 5.2.13 on 2026-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('pnet', 'PNet'), ('careerjunction', 'CareerJunction'), ('careerjunction_it', 'CareerJunction IT'), ('careers24', 'Careers24'), ('jobmail', 'JobMail'), ('gumtree', 'Gumtree'), ('dpsa', 'DPSA'), ('sayouth', 'SAYouth'), ('essa', 'ESSA'), ('govza', 'Gov.za')], max_length=50)),
                ('url', models.TextField(blank=True)),
                ('apply_email', models.CharField(blank=True, max_length=255)),
                ('match_score', models.IntegerField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('how_to_apply', models.TextField(blank=True)),
                ('docs_required', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('title', 'company', 'platform')},
            },
        ),
    ]
