# Generated by Django 5.2.14 on 2026-05-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
