# Generated by Django 5.2.14 on 2026-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_job_closing_date_job_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(choices=[('indeed', 'Indeed'), ('google', 'Google Jobs'), ('pnet', 'PNet'), ('careerjunction', 'CareerJunction'), ('careerjunction_it', 'CareerJunction IT'), ('careers24', 'Careers24'), ('jobmail', 'JobMail'), ('jobvine', 'Jobvine'), ('jobjack', 'JobJack'), ('offerzen', 'OfferZen'), ('executiveplacements', 'Executive Placements'), ('bizcommunity', 'Bizcommunity'), ('jobcrystal', 'JobCrystal'), ('gumtree', 'Gumtree'), ('dpsa', 'DPSA'), ('sayouth', 'SAYouth'), ('essa', 'ESSA'), ('govza', 'Gov.za')], max_length=50),
        ),
    ]
