name: Make & Commit Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "True"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HF_API_KEY: ${{ secrets.HF_API_KEY }}
      HF_MODEL: ${{ secrets.HF_MODEL }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make migrations
        run: |
          python manage.py makemigrations accounts --no-input
          python manage.py makemigrations cv --no-input
          python manage.py makemigrations scraper --no-input
          python manage.py makemigrations mailer --no-input
          python manage.py makemigrations matcher --no-input

      - name: Merge migrations if needed
        run: python manage.py makemigrations --merge --no-input

      - name: Run migrate
        run: python manage.py migrate --no-input

      - name: Commit migration files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/*/migrations/*.py
          git diff --cached --quiet || git commit -m "chore: update migrations [skip ci]"
          git push